# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 0

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud-service'
    organization: 'pietrovb25'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'pietrovb25_MeuLivroDeReceitas'
    cliProjectName: 'MeuLivroDeReceitas'
    cliSources: '.'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'